# Generated by Django 4.2.6 on 2023-10-12 05:48

from django.db import migrations, models
import django.db.models.deletion
import knowledge.services


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='название')),
                ('description', models.TextField(max_length=255, verbose_name='описание')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='knowledge/images', verbose_name='картинка')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
            },
        ),
        migrations.CreateModel(
            name='CourseSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='название')),
                ('description', models.CharField(max_length=255, verbose_name='описание')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='knowledge/images', verbose_name='картинка')),
                ('url_video', models.URLField(blank=True, null=True, verbose_name='ссылка на видео')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pay', models.DateField(verbose_name='дата оплаты')),
                ('value_pay', models.IntegerField(verbose_name='сумма оплаты')),
                ('method_pay', models.CharField(blank=True, choices=[('cash', 'наличные'), ('non_cash', 'безналичный расчет')], null=True, verbose_name='способ оплаты')),
                ('payment_intent_id', models.CharField(default=knowledge.services.gen_random_num, max_length=255, verbose_name='ID оплаты')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge.course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge.lesson')),
            ],
            options={
                'verbose_name': 'оплата',
                'verbose_name_plural': 'оплата',
            },
        ),
    ]
