# Generated by Django 4.2.6 on 2023-10-12 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='last_updated',
        ),
    ]
